// Re-curate the SHIPPED scenic dataset deterministically — NO network, NO LLM.
// Reads src/data/scenicRoutes.ts, then for every route:
//   1. cleans the polyline (dedup + out-and-back spur removal),
//   2. recomputes distanceKm / drivingTime from the cleaned line,
//   3. MEASURES curvature from geometry and writes it into rubric.curvature
//      (replacing the old language-model guess),
//   4. recomputes a transparent, motorcycle-weighted composite score,
//   5. re-aims any heading:0 stops (the schema-default-smell that pointed the
//      camera at the parking lot), and re-sorts the slate by the new score.
// Then rewrites src/data/scenicRoutes.ts in place.
//
// This is the deterministic fix for the audit findings: curvature was hallucinated,
// the score was an opaque LLM number, and 4/6 routes had backtracking spurs.
//
// Run: node scripts/recurate-scenic.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  cleanCoords, curvature10, sinuosityScore, pathLengthKm, compositeScore,
  parseDriveTime, formatDriveTime, COMPOSITE_WEIGHTS,
} from './lib/scenic-metrics.mjs';

const FILE = fileURLToPath(new URL('../src/data/scenicRoutes.ts', import.meta.url));

// View headings for stops the pipeline left at the schema-default 0 (= due north = at the
// parking lot, not the view). Best-effort manual aim until snap-streetview.mjs is run with
// a key. Keyed by stop title.
const HEADING_FIXES = {
  'Whirlpool State Park Rim Overlook': 290, // WNW, down into the gorge / whirlpool
  'Olcott Harbor': 350, // N toward the open lake + pier light
};

function downsample(coords, max) {
  if (coords.length <= max) return coords;
  const step = (coords.length - 1) / (max - 1);
  const out = [];
  for (let i = 0; i < max; i++) out.push(coords[Math.round(i * step)]);
  return out;
}

const txt = readFileSync(FILE, 'utf8');
const routes = JSON.parse(txt.slice(txt.indexOf('= [') + 2, txt.lastIndexOf(';')));

const before = routes.map((r) => ({ id: r.id, score: r.score, curv: r.rubric.curvature, km: r.distanceKm }));

for (const r of routes) {
  const raw = r.coords.map((c) => [c[0], c[1]]);
  const cleaned = cleanCoords(raw);

  const oldKm = r.distanceKm;
  const newKm = pathLengthKm(cleaned);
  const oldMin = parseDriveTime(r.drivingTime);
  // Spur removal only deletes redundant out-and-back miles, so scale the original pace.
  const newMin = oldMin != null && oldKm > 0 ? oldMin * (newKm / oldKm) : oldMin;

  r.coords = downsample(cleaned, 150);
  r.distanceKm = +newKm.toFixed(1);
  if (newMin != null) r.drivingTime = formatDriveTime(newMin);

  // MEASURE curvature from the cleaned geometry; never trust the LLM rubric value.
  r.rubric = { ...r.rubric, curvature: curvature10(r.coords) };

  for (const s of r.stops) {
    if (s.heading === 0 && HEADING_FIXES[s.title] != null) s.heading = HEADING_FIXES[s.title];
  }

  // Transparent, reproducible composite — replaces the opaque LLM 0-100.
  r.score = compositeScore(r.rubric);
}

routes.sort((a, b) => b.score - a.score);

const header =
  `import type { ScenicRoute } from './types';\n\n` +
  `/**\n` +
  ` * Scenic WNY motorcycle routes — generated by the build-time pipeline\n` +
  ` * (gather -> agentic compose/judge/repair -> snap-streetview -> assemble), then\n` +
  ` * deterministically re-curated by scripts/recurate-scenic.mjs.\n` +
  ` * Geometry is OSRM-snapped to real roads and cleaned of duplicate points and\n` +
  ` * out-and-back spurs; rubric.curvature is MEASURED from that geometry (radians/km\n` +
  ` * mapped to 0-10, same scale as the Live-scan tab); scenery/greenery/water/notability\n` +
  ` * come from OSM POIs + the judge panel; score is a transparent motorcycle-weighted\n` +
  ` * composite of the rubric (curvature ${COMPOSITE_WEIGHTS.curvature}, scenery ${COMPOSITE_WEIGHTS.scenery},\n` +
  ` * greenery ${COMPOSITE_WEIGHTS.greenery}, water ${COMPOSITE_WEIGHTS.water}, notability ${COMPOSITE_WEIGHTS.notability}).\n` +
  ` * Do not hand-edit — re-run the pipeline / recurate script.\n` +
  ` */\n`;
writeFileSync(FILE, header + `export const SCENIC_ROUTES: ScenicRoute[] = ${JSON.stringify(routes)};\n`);

// Report
console.log('Re-curated', routes.length, 'routes.\n');
console.log('id'.padEnd(48), 'curv(was→now)  score(was→now)  km(was→now)');
for (const r of routes) {
  const b = before.find((x) => x.id === r.id);
  const radkm = sinuosityScore(r.coords).toFixed(2);
  console.log(
    r.id.padEnd(48),
    `${String(b.curv).padStart(4)}→${String(r.rubric.curvature).padStart(4)}`,
    `   ${String(b.score).padStart(3)}→${String(r.score).padStart(3)}`,
    `   ${String(b.km).padStart(5)}→${String(r.distanceKm).padStart(5)}`,
    `  (${radkm} rad/km)`,
  );
}
console.log('\nNew ranking (top first):', routes.map((r) => r.id).join('  >  '));
console.log('\nWrote', FILE);
